# Generated by Django 5.0 on 2024-01-03 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'категорию',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NewPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок поста')),
                ('text', models.TextField(blank=True, verbose_name='Текст поста')),
                ('tags', models.CharField(max_length=100, verbose_name='Теги')),
                ('crt_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('privacy', models.CharField(choices=[('Публично', 'Публично'), ('Приватно', 'Приватно')], max_length=100, verbose_name='Статус приватности')),
                ('time_to_delete', models.CharField(choices=[('Никогда', 'Никогда'), ('После прочтения', 'После прочтения'), ('10 минут', '10 минут'), ('1 час', '1 час'), ('1 день', '1 день'), ('1 неделя', '1 неделя'), ('2 недели', '2 недели'), ('1 месяц', '1 месяц'), ('6 месяцев', '6 месяцев'), ('1 год', '1 год')], max_length=100, verbose_name='Время удаления поста')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pastebin.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'постов',
                'verbose_name_plural': 'Посты',
                'ordering': ['-crt_time', 'title'],
            },
        ),
    ]
